# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7Nkqxxz-xOQGEcAIme3gBU7SBgx5Ffx
"""

my_list=["apple","banana","cherry"]
my_dict={index:value for index,value in enumerate(my_list)}
print(my_dict)

